{{- define "keystone.sync_db.volumeMounts" -}}
{{- $envAll := index . 0 -}}
volumeMounts:
  - name: keystone-etc
    mountPath: /var/lib/kolla/config_files/keystone.conf
    subPath: keystone.conf
{{- end }}

{{- $local := dict "podVolMounts" false -}}
{{- $envAll := index . -}}
{{- $_ := set $local "podVolMounts" ( index ( tuple . | include "keystone.sync_db.volumeMounts" | toString | fromYaml ) "volumeMounts" ) }}
{{- $dependencyJobs := list "keystone-db-init" -}}
{{- $image := include "keystone.image" . -}}
{{- $dbSyncJob := dict "envAll" . "serviceName" "keystone" "dependencyJobs" $dependencyJobs "podVolMounts" $local.podVolMounts "image" $image -}}
{{ $dbSyncJob | include "common.manifests.job_db_sync" }}
