apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OS_CLUSTER_URL: {{ include "keystone.cluster.endpoint" . | b64enc | quote }}
  OS_DEFAULT_DOMAIN: {{ .Values.admin_default_domain_id | b64enc | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.admin_project_domain_name | b64enc | quote }}
  OS_PROJECT_NAME: {{ .Values.admin_project_name | b64enc | quote }}
  OS_REGION_NAME: {{ .Values.region_name | b64enc | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.admin_user_domain_name | b64enc | quote }}
  OS_USERNAME: {{ .Values.admin_username | b64enc | quote }}
