---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: DaemonSet
metadata:
  name: nova-libvirt
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nova-libvirt
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ include "common.images.kubernetes-entrypoint" (dict "registry" .Values.imageRegistry "namespace" .Values.imageNamespace) | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: PATH
            value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
      containers:
        - name: nova-libvirt
          securityContext:
            privileged: true
          image: {{ template "nova.libvirt.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if .Values.ceph.enabled }}
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - /tmp/secret-ceph-conf.sh
                - /tmp/gen-ceph-conf.sh
          {{- end }}
          env: 
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "nova-libvirt"
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            {{- if .Values.ceph.enabled }}
            - name: ROOK_CEPH_USERNAME
              value: {{ .Values.ceph.cephClientName | quote }}
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ printf "ceph-%s" .Values.ceph.cephClientName | quote }}
                  key: {{ .Values.ceph.cephClientName }}
            - name: RBD_SECRET_UUID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.passwordRelease | quote }}
                  key: "rbd-secret-uuid"
            {{- end }}
          volumeMounts:
            - mountPath: /var/log/kolla/libvirt
              name: kolla-libvirt-log
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/config.json
              subPath: nova-libvirt.json
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/libvirtd.conf
              subPath: libvirtd.conf
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/qemu.conf
              subPath: qemu.conf
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run
              name: run
              mountPropagation: HostToContainer
            - mountPath: /dev
              name: dev
            - mountPath: /sys/fs/cgroup
              name: sys-fs-cgroup
            - mountPath: /var/lib/libvirt
              name: var-lib-libvirt
            - mountPath: /var/etc/qemu
              name: var-etc-qemu
            - mountPath: /var/lib/nova
              name: var-lib-nova
            {{- if .Values.ceph.enabled }}
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/ceph
              name: etc-ceph
            - mountPath: /etc/libvirt/secrets
              name: etc-libvirt-secrets
            - mountPath: /tmp/gen-ceph-conf.sh
              name: nova-bin
              subPath: gen-ceph-conf.sh
            - mountPath: /tmp/secret-ceph-conf.sh
              name: nova-bin
              subPath: secret-ceph-conf.sh
            - mountPath: /etc/rook
              name: mon-endpoint-volume  
            {{- end }}
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - hostPath:
            path: /var/log/kolla/libvirt
            type: DirectoryOrCreate
          name: kolla-libvirt-log
        - name: nova-etc
          configMap:
            name: nova-etc
        - hostPath:
            path: /lib/modules
            type: DirectoryOrCreate
          name: lib-modules
        - hostPath:
            path: /run
            type: DirectoryOrCreate
          name: run
        - hostPath:
            path: /dev
            type: DirectoryOrCreate
          name: dev
        - hostPath:
            path: /sys/fs/cgroup
            type: DirectoryOrCreate
          name: sys-fs-cgroup
        - hostPath:
            path: /var/lib/libvirt
            type: DirectoryOrCreate
          name: var-lib-libvirt
        - hostPath:
            path: /var/etc/qemu
            type: DirectoryOrCreate
          name: var-etc-qemu
        - hostPath:
            path: /var/lib/nova
            type: DirectoryOrCreate
          name: var-lib-nova
          {{- if .Values.ceph.enabled }}
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: etc-ceph
        - emptyDir: {}
          name: etc-libvirt-secrets
        - name: mon-endpoint-volume
          configMap:
            name: ceph-monitor-endpoints
            items:
              - key: data
                path: mon-endpoints
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0755
        {{- end }}
