{{- if .Values.enabled_vnc }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: nova-novncproxy
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: novncproxy-api
    spec:
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ include "common.images.kubernetes-entrypoint" (dict "registry" .Values.imageRegistry "namespace" .Values.imageNamespace) | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: DEPENDENCY_JOBS
            value: "nova-db-sync,nova-register"
      containers:
        - name: nova-novncproxy
          securityContext:
            privileged: true
          image: {{ template "nova.novncproxy.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if .Values.enableLivenessProbe }}
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6080
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          {{- if .Values.enableReadinessProbe }}
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6080
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          env: 
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "nova-novncproxy"
          ports:
            - name: novncproxy-api
              containerPort: 6080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/kolla/nova
              name: kollalog
              mountPropagation: HostToContainer
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/config.json
              subPath: nova-novncproxy.json
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/nova.conf
              subPath: nova.conf
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - hostPath:
            path: /var/log/kolla/nova
            type: DirectoryOrCreate
          name: kollalog
        - configMap:
            defaultMode: 420
            name: nova-etc
          name: nova-etc
{{- end }}
