apiVersion: batch/v1
kind: Job
metadata:
  name: nova-gen-ssh-key
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    spec:
      activeDeadlineSeconds: 100
      containers:
      - name: gen-nova-ssh-key
        image: {{ template "nova.ssh.image" . }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - python3 /tmp/gen-ssh-key.py
        env:
          - name: SSH_SECRET_NAME
            value: nova-ssh
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /tmp/gen-ssh-key.py
            name: nova-bin
            subPath: gen-ssh-key.py
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - name: nova-bin
          configMap:
            defaultMode: 0755
            name: nova-bin
