{{- define "glance.render.podEnvVars" -}}
{{- $envAll := index . 0 -}}
env:
  - name: CONF_FILE_NAME
    value: glance-api.conf
{{- end -}}

{{- $envAll := index . -}}
{{- $podEnvVars := tuple . | include "glance.render.podEnvVars" | toString | fromYaml }}
{{- $dependencyJobs := list "glance-update-openstack-conn-info" -}}
{{- $cmRenderJob := dict "envAll" . "serviceName" "glance" "dependencyJobs" $dependencyJobs "podEnvVars" $podEnvVars.env -}}
{{ $cmRenderJob | include "common.manifests.job_cm_render" }}
