#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

## @section Cluster Paramters
## @param cluster_domain_suffix [t#Cluster Domain Suffix] The doamin suffix of the current k8s cluster
cluster_domain_suffix: cluster.local

## @section Dependency Parameters
## @param openstackDepRelease [t#Openstack-dep Release] The release name of openstack-dep chart
openstackDepRelease: "openstack-dependency"
## @param passwordRelease [t#Password Release] The release name of password chart
passwordRelease: "openstack-password"
## @param keystoneRelease [t#keystone Release] The release name of keystone chart
keystoneRelease: "openstack-keystone"

## @section Image Parameters
## @param imageRegistry [t#Image Registry] The registry address of openstack kolla image
imageRegistry: "registry.aliyuncs.com"
## @param imageNamespace [t#Image Namespace] The registry namespace of openstack kolla image
imageNamespace: "kolla-helm"
## @param openstackTag [t#Openstack version] The openstack version
openstackTag: "yoga"
## @param pullPolicy [t#Pull Policy] The image pull policy
pullPolicy: "IfNotPresent"

## @section Deployment Parameters
## @param replicaCount Number of placement replicas to deploy (requires ReadWriteMany PVC support)
replicaCount: 1
## @param serviceAccountName ServiceAccount name
serviceAccountName: placement
## @param enableLivenessProbe [t#Enable Liveness Probe] Whether or not enable liveness probe
enableLivenessProbe: true
## @param enableReadinessProbe [t#Enable Readliness Probe] Whether or not enable readiness probe
enableReadinessProbe: true

## @section placement Config parameters
## @param db_database [t#Placement database] The placement database name
db_database: placement
## @param db_username [t#Placement Database User] The placement database user name
db_username: placement
## @param enabled_notification [t#Enable Notification] Whether or not enable notification
enabled_notification: false

## @section Ingress Parameters
## @param ingress.enabled [t#Ingress] Whether or not create ingress for placement service
## @param ingress.ingressClass [t#Ingress Class] Ingress Class Name
## @param ingress.path [t#Path Prefix] Ingress will match the path prefix, and forward the matched request to placement service
ingress:
  enabled: true
  ingressClass: openstack-nginx
  path: placement
