apiVersion: v2
dependencies:
- name: common
  repository: https://kungze.github.io/kolla-helm
  version: 1.x.x
description: Openstack nova service
home: https://github.com/kungze/kolla-helm
maintainers:
- name: Kungze
name: nova
version: 1.0.0
