apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  namespace: {{ .Release.Namespace | quote }}
data:
  kolla-toolbox-sudoer: |
    ansible ALL=(ALL) NOPASSWD: ALL
  cinder.conf: |
{{ tuple "conf/_cinder.conf.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-wsgi.conf: |
{{ tuple "conf/_cinder_wsgi.conf.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-scheduler.json: |
{{ tuple "conf/_cinder_scheduler.json.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-volume.json: |
{{ tuple "conf/_cinder_volume.json.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-api.json: |
{{ tuple "conf/_cinder_api.json.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-backup.json: |
{{ tuple "conf/_cinder_backup.json.tpl" . | include "common.utils.template" | indent 4 }}
  db-sync.json: |
{{ tuple "conf/_cinder_db_sync.json.tpl" . | include "common.utils.template" | indent 4 }}
  {{- if eq .Values.lvm.lvm_target_helper "tgtadm" }}
  tgtd.json: |
{{ tuple "conf/_tgtd.json.tpl" . | include "common.utils.template" | indent 4 }}
  {{- end }}
