apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc
  namespace: {{ .Release.Namespace | quote }}
data:
  kolla-toolbox-sudoer: |
    ansible ALL=(ALL) NOPASSWD: ALL
  db-sync.json: |
{{ tuple "conf/_neutron_db_sync.json.tpl" . | include "common.utils.template" | indent 4 }}
  neutron.conf: |
{{ tuple "conf/neutron-server/_neutron.conf.tpl" . | include "common.utils.template" | indent 4 }}
  neutron-server.json: |
{{ tuple "conf/neutron-server/_neutron-server.json.tpl" . | include "common.utils.template" | indent 4 }}
  ml2_conf.ini: |
{{ tuple "conf/neutron-server/_ml2_conf.ini.tpl" . | include "common.utils.template" | indent 4}}
  neutron-dhcp-agent.json : |
{{ tuple "conf/neutron-dhcp-agent/_neutron-dhcp-agent.json.tpl" . | include "common.utils.template" | indent 4}}
  dhcp_agent.ini: |
{{ tuple "conf/neutron-dhcp-agent/_dhcp_agent.ini.tpl" . | include "common.utils.template" | indent 4}}
  dnsmasq.conf: |
{{ tuple "conf/neutron-dhcp-agent/_dnsmasq.conf.tpl" . | include "common.utils.template" | indent 4}} 
  neutron-l3-agent.json: |
{{ tuple "conf/neutron-l3-agent/_neutron-l3-agent.json.tpl" . | include "common.utils.template" | indent 4 }}
  fwaas_driver.ini: |
{{ tuple "conf/neutron-l3-agent/_fwaas_driver.ini.tpl" . | include "common.utils.template" | indent 4 }}
  l3_agent.ini: |
{{ tuple "conf/neutron-l3-agent/_l3_agent.ini.tpl" . | include "common.utils.template" | indent 4 }}
  neutron_vpnaas.conf: |
{{ tuple "conf/neutron-l3-agent/_neutron_vpnaas.conf.tpl" . | include "common.utils.template" | indent 4 }}
  neutron-l3-agent-wrapper.sh: |
{{ tuple "conf/neutron-l3-agent/_neutron-l3-agent-wrapper.sh.tpl" . | include "common.utils.template" | indent 4 }}
  metadata_agent.ini: |
{{ tuple "conf/neutron-metadata-agent/_metadata_agent.ini.tpl" . | include "common.utils.template" | indent 4 }}
  neutron-metadata-agent.json: |
{{ tuple "conf/neutron-metadata-agent/_neutron-metadata-agent.json.tpl" . | include "common.utils.template" | indent 4 }}



{{- if .Values.neutron_linuxbridge_agent.enabled}}
  neutron-linuxbridge-agent.json: |
{{ tuple "conf/neutron-linuxbridge-agent/_neutron-linuxbridge-agent.json.tpl" . | include "common.utils.template" | indent 4}}
  linuxbridge_agent.ini: |
{{ tuple "conf/neutron-linuxbridge-agent/_linuxbridge_agent.ini.tpl" . | include "common.utils.template" | indent 4}}
{{- end }}

{{- if .Values.neutron_openvswitch_agent.enabled}}
  kolla-toolbox.json: |
{{ tuple "conf/neutron-openvswitch-agent/_kolla-toolbox.json.tpl" . | include "common.utils.template" | indent 4}}
  neutron-openvswitch-agent.json: |
{{ tuple "conf/neutron-openvswitch-agent/_neutron-openvswitch-agent.json.tpl" . | include "common.utils.template" | indent 4}}
  openvswitch_agent.ini: |
{{ tuple "conf/neutron-openvswitch-agent/_openvswitch_agent.ini.tpl" . | include "common.utils.template" | indent 4}}
  openvswitch-db-server.json: |
{{ tuple "conf/neutron-openvswitch-agent/_openvswitch-db-server.json.tpl" . | include "common.utils.template" | indent 4}}
  start-ovsdb-server: |
{{ tuple "conf/neutron-openvswitch-agent/_start-ovsdb-server.tpl" . | include "common.utils.template" | indent 4}}
  openvswitch-vswitchd.json: |
{{ tuple "conf/neutron-openvswitch-agent/_openvswitch-vswitchd.json.tpl" . | include "common.utils.template" | indent 4}}
  start-ovs: |
{{ tuple "conf/neutron-openvswitch-agent/_start-ovs.tpl" . | include "common.utils.template" | indent 4}}
{{- end }}
