{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-bin
  namespace: {{ .Release.Namespace | quote }}
data:
  db-init.sh: |
{{- include "common.scripts.db_init" . | indent 4 }}
  db-sync.sh: |
{{- include "common.scripts.db_sync" . | indent 4 }}
  ks-register-services.sh: |
{{- include "common.scripts.ks_register_services" . | indent 4  }}
  ks-register-users.sh: |
{{- include "common.scripts.ks_register_users" . | indent 4  }}
  configmap-render.py: |
{{ include "common.scripts.configmap_render" . | indent 4 }}
  update-openstack-conn-info.py: |
{{- include "common.scripts.update_openstack_conn_info" . | indent 4  }}
{{- if .Values.neutron_openvswitch_agent.enabled}}
  neutron-configmap-render.py: |
{{ tuple "bin/_neutron-configmap-render.py.tpl" . | include "common.utils.template" | indent 4}}
{{- end}}
