---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: neutron-server
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: neutron-api
    spec:
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ include "common.images.kubernetes-entrypoint" (dict "registry" .Values.imageRegistry "namespace" .Values.imageNamespace) | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: DEPENDENCY_JOBS
            value: "neutron-db-sync,neutron-register"
      containers:
        - name: neutron-server
          securityContext:
            privileged: true
          image: {{ template "neutron.server.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if .Values.enableLivenessProbe }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 9696
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          {{- if .Values.enableReadinessProbe }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 9696
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          env: 
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "neutron-server"
          ports:
            - name: neutron-server
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/kolla/neutron
              name: kollalog
              mountPropagation: HostToContainer
            - name: neutron-etc
              mountPath: /var/lib/kolla/config_files/config.json
              subPath: neutron-server.json
            - name: neutron-etc
              mountPath: /var/lib/kolla/config_files/neutron.conf
              subPath: neutron.conf
            - name: neutron-etc
              mountPath: /var/lib/kolla/config_files/ml2_conf.ini
              subPath: ml2_conf.ini
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
        - hostPath:
            path: /var/log/kolla/neutron
            type: DirectoryOrCreate
          name: kollalog
        - configMap:
            defaultMode: 420
            name: neutron-etc
          name: neutron-etc
